window.STORE_DATA = {
  site: {
    name: "NovaStore",
    tagline: "Discover smarter digital products, services & deals.",
    url: "https://example.com",
    locale: "en_IN",
    currency: "INR"
  },

  categories: [
    {slug:"apps", name:"Apps", icon:"📱", tone:"blue", desc:"Useful mobile and web apps for everyday work."},
    {slug:"games", name:"Games", icon:"🎮", tone:"violet", desc:"Popular games, entertainment and gaming utilities."},
    {slug:"software", name:"Software", icon:"💻", tone:"cyan", desc:"Desktop software, productivity and creator tools."},
    {slug:"ai-tools", name:"AI Tools", icon:"✦", tone:"pink", desc:"AI-powered tools for writing, images, video and productivity."},
    {slug:"banks", name:"Banks", icon:"🏦", tone:"emerald", desc:"Banking products, accounts and financial services."},
    {slug:"credit-cards", name:"Credit Cards", icon:"💳", tone:"amber", desc:"Compare popular cards and their key benefits."},
    {slug:"loans", name:"Loans", icon:"₹", tone:"orange", desc:"Loan discovery with rates, eligibility and transparent considerations."},
    {slug:"investments", name:"Investments", icon:"📈", tone:"green", desc:"Investment platforms and wealth-building services."},
    {slug:"insurance", name:"Insurance", icon:"🛡", tone:"teal", desc:"Insurance products, quotes and coverage discovery."},
    {slug:"shopping", name:"Shopping", icon:"🛍", tone:"rose", desc:"Shopping platforms and useful product destinations."},
    {slug:"deals", name:"Deals", icon:"⚡", tone:"red", desc:"Limited-time deals, offers and value picks."},
    {slug:"services", name:"Services", icon:"🧰", tone:"slate", desc:"Digital services, subscriptions and useful platforms."},
    {slug:"templates", name:"Templates", icon:"▦", tone:"indigo", desc:"Ready-to-use templates for websites, docs and content."},
    {slug:"ebooks", name:"E-books", icon:"📚", tone:"fuchsia", desc:"Guides, books and educational digital reading."}
  ],

  products: [
    {
      slug:"notion",
      title:"Notion",
      category:"software",
      subcategory:"Productivity",
      badge:"Popular",
      rating:4.8,
      price:"Free / Paid",
      image:"https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=900&q=80",
      short:"All-in-one workspace for notes, docs, tasks and wikis.",
      description:"A flexible workspace for building documentation, project boards, notes, knowledge bases and repeatable workflows.",
      features:["Docs & notes","Databases","Tasks","Team collaboration"],
      tags:["productivity","notes","workspace","team","docs"],
      actionText:"Visit",
      url:"https://www.notion.so/",
      pros:["Flexible for many workflows","Strong collaboration","Large template ecosystem"],
      considerations:["Some advanced features are paid","Can require setup time"]
    },
    {
      slug:"canva",
      title:"Canva",
      category:"apps",
      subcategory:"Design",
      badge:"Editor's pick",
      rating:4.8,
      price:"Free / Paid",
      image:"https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=900&q=80",
      short:"Fast visual design platform for social posts, presentations and more.",
      description:"Create social graphics, presentations, posters, documents, video content and branded assets with a browser-first workflow.",
      features:["Design templates","Presentations","Social graphics","Video"],
      tags:["design","graphics","social","templates","video"],
      actionText:"Visit",
      url:"https://www.canva.com/",
      pros:["Very approachable","Huge template library","Works in browser"],
      considerations:["Advanced brand tools may require paid plans","Template-heavy workflows can feel less custom"]
    },
    {
      slug:"chatgpt",
      title:"ChatGPT",
      category:"ai-tools",
      subcategory:"AI Assistant",
      badge:"Trending",
      rating:4.9,
      price:"Free / Paid",
      image:"https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=80",
      short:"AI assistant for writing, research, coding, brainstorming and analysis.",
      description:"A general-purpose AI assistant for drafting, summarizing, coding, ideation and structured problem solving.",
      features:["Conversation","Writing","Coding","Analysis"],
      tags:["ai","assistant","writing","coding","research"],
      actionText:"Get Started",
      url:"https://chatgpt.com/",
      pros:["Broad use cases","Strong writing and coding workflows","Easy to start"],
      considerations:["Outputs should be reviewed","Capabilities and limits vary by plan"]
    },
    {
      slug:"spotify",
      title:"Spotify",
      category:"apps",
      subcategory:"Entertainment",
      badge:"Popular",
      rating:4.7,
      price:"Free / Premium",
      image:"https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=80",
      short:"Music and podcast streaming with personalized discovery.",
      description:"Streaming service with playlists, recommendations, podcasts and cross-device playback.",
      features:["Music streaming","Podcasts","Playlists","Recommendations"],
      tags:["music","podcast","streaming","entertainment"],
      actionText:"Visit",
      url:"https://open.spotify.com/",
      pros:["Excellent discovery","Cross-platform","Large catalog"],
      considerations:["Free tier has limitations","Catalog can vary by region"]
    },
    {
      slug:"steam",
      title:"Steam",
      category:"games",
      subcategory:"Game Store",
      badge:"Gaming",
      rating:4.8,
      price:"Varies",
      image:"https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80",
      short:"Large PC gaming marketplace with community features.",
      description:"A major PC game distribution platform with games, community tools, wishlists, reviews and frequent sales.",
      features:["PC games","Sales","Community","Cloud saves"],
      tags:["gaming","pc","games","deals","store"],
      actionText:"Visit",
      url:"https://store.steampowered.com/",
      pros:["Huge catalog","Frequent discounts","Strong community features"],
      considerations:["Prices and availability vary by region","Requires compatible hardware"]
    },
    {
      slug:"figma",
      title:"Figma",
      category:"software",
      subcategory:"Design",
      badge:"Pro",
      rating:4.8,
      price:"Free / Paid",
      image:"https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=900&q=80",
      short:"Collaborative interface design and prototyping platform.",
      description:"Design interfaces, prototypes and systems together in real time with shared collaboration workflows.",
      features:["UI design","Prototyping","Components","Collaboration"],
      tags:["design","ui","ux","prototype","collaboration"],
      actionText:"Visit",
      url:"https://www.figma.com/",
      pros:["Excellent real-time collaboration","Strong component workflows","Browser based"],
      considerations:["Advanced workflows take learning","Team features vary by plan"]
    },
    {
      slug:"google-drive",
      title:"Google Drive",
      category:"services",
      subcategory:"Cloud Storage",
      badge:"Utility",
      rating:4.7,
      price:"Free / Paid",
      image:"https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=900&q=80",
      short:"Cloud storage and file collaboration across devices.",
      description:"Store files, share folders and collaborate with Docs, Sheets and other Google Workspace tools.",
      features:["Cloud storage","File sharing","Collaboration","Sync"],
      tags:["cloud","storage","files","google","backup"],
      actionText:"Visit",
      url:"https://drive.google.com/",
      pros:["Easy collaboration","Excellent ecosystem integration","Simple sharing"],
      considerations:["Storage quotas apply","Privacy settings should be reviewed"]
    },
    {
      slug:"amazon",
      title:"Amazon",
      category:"shopping",
      subcategory:"Marketplace",
      badge:"Marketplace",
      rating:4.6,
      price:"Varies",
      image:"https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=900&q=80",
      short:"Large online marketplace spanning electronics, home, books and more.",
      description:"Online shopping destination with a wide range of categories, delivery options and seller listings.",
      features:["Marketplace","Fast delivery options","Product reviews","Wishlists"],
      tags:["shopping","marketplace","electronics","deals"],
      actionText:"Shop",
      url:"https://www.amazon.in/",
      pros:["Broad product selection","Convenient discovery","Strong logistics in many regions"],
      considerations:["Seller quality varies","Compare pricing before purchase"]
    },
    {
      slug:"hostinger",
      title:"Hostinger",
      category:"services",
      subcategory:"Hosting",
      badge:"Web",
      rating:4.7,
      price:"Paid",
      image:"https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=900&q=80",
      short:"Web hosting and domain services for websites and apps.",
      description:"Hosting provider offering website hosting, domains, managed WordPress and related web infrastructure.",
      features:["Web hosting","Domains","WordPress","SSL"],
      tags:["hosting","website","domain","wordpress","server"],
      actionText:"Visit",
      url:"https://www.hostinger.com/",
      pros:["Beginner friendly","Wide hosting portfolio","Website builder options"],
      considerations:["Introductory and renewal pricing can differ","Compare plan resources"]
    },
    {
      slug:"hdfc-bank",
      title:"HDFC Bank",
      category:"banks",
      subcategory:"Banking",
      badge:"Financial",
      rating:4.5,
      price:"Varies",
      image:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=80",
      short:"Indian banking services including accounts, cards and digital banking.",
      description:"Banking provider with consumer and business financial services. Review current terms, fees and eligibility directly with the provider.",
      features:["Accounts","Cards","Digital banking","Loans"],
      tags:["bank","banking","account","india","finance"],
      actionText:"Visit",
      url:"https://www.hdfcbank.com/",
      pros:["Broad product range","Digital banking options","Established provider"],
      considerations:["Fees and rates change","Eligibility and approval are provider-dependent"],
      financial:true
    },
    {
      slug:"icici-credit-card",
      title:"ICICI Bank Credit Cards",
      category:"credit-cards",
      subcategory:"Cards",
      badge:"Compare",
      rating:4.4,
      price:"Varies",
      image:"https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=900&q=80",
      short:"Credit card portfolio with rewards, cashback and travel-focused options.",
      description:"Explore card variants and compare rewards, fees, eligibility and benefits on the issuer's current pages.",
      features:["Rewards","Cashback options","Travel cards","Digital application"],
      tags:["credit card","cards","cashback","rewards","finance"],
      actionText:"Apply",
      url:"https://www.icicibank.com/personal-banking/cards/credit-card",
      pros:["Multiple card variants","Different rewards structures","Online application options"],
      considerations:["Fees vary by card","Approval is subject to issuer criteria"],
      financial:true
    },
    {
      slug:"personal-loan-discovery",
      title:"Personal Loan Discovery",
      category:"loans",
      subcategory:"Personal Loan",
      badge:"Financial",
      rating:4.2,
      price:"Rate varies",
      image:"https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=900&q=80",
      short:"A discovery page for comparing loan options and understanding key terms.",
      description:"Use lender pages to compare current interest rates, processing fees, tenure, eligibility and repayment obligations.",
      features:["Rate comparison","Eligibility review","Tenure options","Online application"],
      tags:["loan","personal loan","finance","credit","emi"],
      actionText:"Explore",
      url:"https://www.google.com/search?q=personal+loan+India",
      pros:["Makes comparisons easier","Encourages checking key loan terms","Useful starting point"],
      considerations:["Rates are personalized","Do not borrow without understanding total repayment"],
      financial:true
    },
    {
      slug:"groww",
      title:"Groww",
      category:"investments",
      subcategory:"Investing",
      badge:"Popular",
      rating:4.5,
      price:"Varies",
      image:"https://images.unsplash.com/photo-1559526324-593bc073d938?auto=format&fit=crop&w=900&q=80",
      short:"Investment platform for discovering mutual funds, stocks and more.",
      description:"Investment platform covering products such as mutual funds and stocks. Verify current charges, risks and suitability before investing.",
      features:["Mutual funds","Stocks","Portfolio tracking","Digital onboarding"],
      tags:["investment","stocks","mutual funds","finance","wealth"],
      actionText:"Visit",
      url:"https://groww.in/",
      pros:["Easy digital interface","Broad investment discovery","Portfolio tools"],
      considerations:["Market investments carry risk","Fees and product availability can change"],
      financial:true
    },
    {
      slug:"acko",
      title:"ACKO",
      category:"insurance",
      subcategory:"Insurance",
      badge:"Digital",
      rating:4.3,
      price:"Quote based",
      image:"https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=80",
      short:"Digital-first insurance discovery and policy services.",
      description:"Explore insurance products and current coverage details directly with the insurer, including exclusions and claim terms.",
      features:["Online quotes","Policy management","Motor insurance","Health insurance"],
      tags:["insurance","health","motor","policy","quote"],
      actionText:"Get Quote",
      url:"https://www.acko.com/",
      pros:["Digital onboarding","Quote-led discovery","Online policy management"],
      considerations:["Coverage exclusions matter","Premiums depend on profile and policy"]
    },
    {
      slug:"html5-premium-template",
      title:"Aurora Pro HTML Template",
      category:"templates",
      subcategory:"Website Template",
      badge:"Digital",
      rating:4.7,
      price:"₹499",
      image:"https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?auto=format&fit=crop&w=900&q=80",
      short:"Premium responsive starter template for modern landing pages.",
      description:"A polished front-end template concept for portfolios, product launches and service websites.",
      features:["Responsive","Dark mode","Landing sections","Fast CSS"],
      tags:["template","html","website","landing","dark mode"],
      actionText:"Buy",
      url:"https://example.com/",
      pros:["Modern visual system","Easy customization","Mobile-first structure"],
      considerations:["Third-party assets may have separate licenses","Review included components before reuse"]
    },
    {
      slug:"startup-guide",
      title:"Startup Operating Guide",
      category:"ebooks",
      subcategory:"Business",
      badge:"Guide",
      rating:4.6,
      price:"₹199",
      image:"https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=900&q=80",
      short:"Practical digital guide for planning, validation and repeatable workflows.",
      description:"An educational digital product concept focused on business planning, experimentation and structured execution.",
      features:["Planning framework","Checklists","Execution system","Digital format"],
      tags:["ebook","business","startup","guide","planning"],
      actionText:"Buy",
      url:"https://example.com/",
      pros:["Action-oriented structure","Useful checklists","Easy digital format"],
      considerations:["Educational material only","Results depend on execution and context"]
    },
    {
      slug:"deal-alert-bundle",
      title:"Weekly Digital Deal Bundle",
      category:"deals",
      subcategory:"Deal",
      badge:"Deal",
      rating:4.4,
      price:"From ₹99",
      image:"https://images.unsplash.com/photo-1607082349566-187342175e2f?auto=format&fit=crop&w=900&q=80",
      short:"A rotating collection of useful digital tools and discounted products.",
      description:"Deal discovery concept for rotating digital products. Verify offer expiry, seller terms and final pricing before purchase.",
      features:["Rotating offers","Digital products","Price checks","Deal alerts"],
      tags:["deals","discount","offer","digital","shopping"],
      actionText:"Explore",
      url:"https://example.com/",
      pros:["Promotes price comparison","Useful for bargain discovery","Easy to revisit"],
      considerations:["Offers can expire","Final price and terms should be checked"]
    }
  ]
};